/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ordersys;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;

import javax.swing.JTable;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ZamriPC
 */
public class MainUI extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        food1.addMouseListener(this); 
        food2.addMouseListener(this); 
        food3.addMouseListener(this); 
        food4.addMouseListener(this); 
        food5.addMouseListener(this); 
        drink1.addMouseListener(this); 
        drink2.addMouseListener(this); 
        drink3.addMouseListener(this); 
        drink4.addMouseListener(this); 
        drink5.addMouseListener(this); 
        dessert1.addMouseListener(this); 
        dessert2.addMouseListener(this); 
        dessert3.addMouseListener(this); 
        dessert4.addMouseListener(this); 
        dessert5.addMouseListener(this); 
        dessert6.addMouseListener(this); 
        
        jTable1.setForeground(Color.yellow);
        jTable1.setBackground(Color.black);
        jTable1.setOpaque(false);
        jTable1.setFont(new Font("Serif",Font.BOLD,16));    
    }
    DefaultTableModel model = new DefaultTableModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        food2 = new javax.swing.JLabel();
        food1 = new javax.swing.JLabel();
        food3 = new javax.swing.JLabel();
        food4 = new javax.swing.JLabel();
        food5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        drink2 = new javax.swing.JLabel();
        drink1 = new javax.swing.JLabel();
        drink3 = new javax.swing.JLabel();
        drink4 = new javax.swing.JLabel();
        drink5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        dessert1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        dessert2 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        dessert3 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        dessert4 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        dessert5 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        dessert6 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtsub = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Order System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Blackadder ITC", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("NAZA Restaurant");

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 0));
        jLabel23.setText("MENU ORDER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(415, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(401, 401, 401))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        food2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/food2.png"))); // NOI18N
        food2.setText("jLabel2");
        jPanel2.add(food2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 13, 120, -1));

        food1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/food1.png"))); // NOI18N
        food1.setText("jLabel2");
        jPanel2.add(food1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 120, -1));

        food3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/food3.png"))); // NOI18N
        food3.setText("jLabel2");
        jPanel2.add(food3, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 13, 120, -1));

        food4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/food4.png"))); // NOI18N
        food4.setText("jLabel2");
        jPanel2.add(food4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 189, 120, -1));

        food5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/food5.png"))); // NOI18N
        food5.setText("jLabel2");
        jPanel2.add(food5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 189, 120, -1));

        jLabel2.setText("Nasi Lemak Ayam");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 137, -1, -1));

        jLabel3.setText("RM 6");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 157, -1, -1));

        jLabel4.setText("Nasi Kukus Ayam");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 137, -1, -1));

        jLabel5.setText("RM 7");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 157, -1, -1));

        jLabel6.setText("Nasi Lemak Sotong");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 137, -1, -1));

        jLabel7.setText("RM 12");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 157, -1, -1));

        jLabel8.setText("Nasi Minyak Ayam");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 313, -1, -1));

        jLabel10.setText("RM 8");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 333, -1, -1));

        jLabel11.setText("Nasi Kerabu Ayam");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 313, -1, -1));

        jLabel12.setText("RM 9");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 333, -1, -1));

        jTabbedPane1.addTab("Food", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        drink2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/drink2.png"))); // NOI18N
        drink2.setText("jLabel2");

        drink1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/drink1.png"))); // NOI18N
        drink1.setText("jLabel2");

        drink3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/drink3.png"))); // NOI18N
        drink3.setText("jLabel2");

        drink4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/drink4.png"))); // NOI18N
        drink4.setText("jLabel2");

        drink5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/drink5.png"))); // NOI18N
        drink5.setText("jLabel2");

        jLabel13.setText("Fresh Orange");

        jLabel14.setText("RM 5");

        jLabel15.setText("Milo Ice");

        jLabel16.setText("RM 4");

        jLabel17.setText("Syrup Ice");

        jLabel18.setText("RM 3");

        jLabel19.setText("Tea Ice");

        jLabel20.setText("RM 2");

        jLabel21.setText("Lime Juice");

        jLabel22.setText("RM 5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drink1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drink2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drink3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drink4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(drink5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drink1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drink2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drink3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(drink4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(drink5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Drink", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        dessert1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/dessert1.png"))); // NOI18N
        dessert1.setText("jLabel2");

        jLabel26.setText("Caramel");

        jLabel27.setText("RM 6");

        dessert2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/dessert2.png"))); // NOI18N
        dessert2.setText("jLabel2");

        jLabel28.setText("Donut");

        jLabel29.setText("RM 1");

        dessert3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/dessert3.png"))); // NOI18N
        dessert3.setText("jLabel2");

        jLabel30.setText("Onde-Onde");

        jLabel31.setText("RM 4");

        dessert4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/dessert4.png"))); // NOI18N
        dessert4.setText("jLabel2");

        jLabel32.setText("Ais Kacang");

        jLabel33.setText("RM 3");

        jLabel34.setText("RM 18");

        dessert5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/dessert5.png"))); // NOI18N
        dessert5.setText("jLabel2");

        jLabel35.setText("Chocolate Cake");

        dessert6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/dessert6.png"))); // NOI18N
        dessert6.setText("jLabel2");

        jLabel36.setText("Seri Muka");

        jLabel37.setText("RM 1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dessert1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dessert2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dessert3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dessert4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(dessert5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dessert6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(dessert3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(dessert2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(dessert1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(dessert4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(dessert5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(dessert6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dessert", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 141, -1, 430));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 163, 611, 214));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setText(" Total Order");
        jLabel9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 408, 208, -1));

        txtsub.setEditable(false);
        txtsub.setBackground(new java.awt.Color(255, 255, 255));
        txtsub.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtsub.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubActionPerformed(evt);
            }
        });
        getContentPane().add(txtsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 408, 149, 43));

        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRemove.setText("Remove Item");
        btnRemove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 526, 174, -1));

        btnOrder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnOrder.setText("Place Order");
        btnOrder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 469, 174, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordersys/background.png"))); // NOI18N
        jLabel24.setText("jLabel24");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 670));

        jLabel25.setText("jLabel25");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 430, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubActionPerformed
    }//GEN-LAST:event_txtsubActionPerformed
    //remove order button
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        //delete row
        if(jTable1.getSelectedRowCount()==1){
            tblModel.removeRow(jTable1.getSelectedRow());
            int sum = 0;

            for(int i = 0; i<jTable1.getRowCount(); i++)
            {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }
            txtsub.setText( Integer.toString(sum));

        }else{
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Table is Empty.");
            }else{
                JOptionPane.showMessageDialog(this, "Please select Single Row for Delete.");
            }
        }

    }//GEN-LAST:event_btnRemoveActionPerformed

    //order button
    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        
        if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Please select order first.","Error", JOptionPane.ERROR_MESSAGE);
            }else{
                int response = JOptionPane.showConfirmDialog(this, "Are you Satisfied with the order.", "Confirm Your Order", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                
                if(response==JOptionPane.YES_OPTION){
                    System.out.println("Yes.. Option is selected");
                                int sum = 0;
            
            for(int i = 0; i<jTable1.getRowCount(); i++)
            {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }  
                    JOptionPane.showMessageDialog(this,"Order Success" + "\nTotal to be paid is: RM" + sum );
                    model = (DefaultTableModel)jTable1.getModel();
                    model.setRowCount(0);
                    txtsub.setText(" ");
                    
                }
                else if(response==JOptionPane.NO_OPTION){
                    System.out.println("No.. Option is selected");
                }
            }
    }//GEN-LAST:event_btnOrderActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    } //main program

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel dessert1;
    private javax.swing.JLabel dessert2;
    private javax.swing.JLabel dessert3;
    private javax.swing.JLabel dessert4;
    private javax.swing.JLabel dessert5;
    private javax.swing.JLabel dessert6;
    private javax.swing.JLabel drink1;
    private javax.swing.JLabel drink2;
    private javax.swing.JLabel drink3;
    private javax.swing.JLabel drink4;
    private javax.swing.JLabel drink5;
    private javax.swing.JLabel food1;
    private javax.swing.JLabel food2;
    private javax.swing.JLabel food3;
    private javax.swing.JLabel food4;
    private javax.swing.JLabel food5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtsub;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {   
        if(e.getSource()== food1)
        {
            String name = "Nasi Lemak Ayam";
            int price = 6;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== food2)
        {
            String name = "Nasi Ayam Kukus";
            int price = 7;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== food3)
        {
            String name = "Nasi Lemak Sotong";
            int price = 12;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== food4)
        {
            String name = "Nasi Minyak Ayam";
            int price = 8;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== food5)
        {
            String name = "Nasi Kerabu";
            int price = 9;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== drink1)
        {
            String name = "Orange Juice";
            int price = 5;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== drink2)
        {
            String name = "Milo Ice";
            int price = 4;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== drink3)
        {
            String name = "Syrup Ice";
            int price = 3;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== drink4)
        {
            String name = "Tea Ice";
            int price = 2;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== drink5)
        {
            String name = "Lime Juice";
            int price = 5;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== dessert1)
        {
            String name = "Caramel";
            int price = 6;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== dessert2)
        {
            String name = "Donut";
            int price = 1;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== dessert3)
        {
            String name = "Onde-Onde";
            int price = 6;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== dessert4)
        {
            String name = "Ais Kacang";
            int price = 3;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== dessert5)
        {
            String name = "Chocolate Cake";
            int price = 18;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
            else if(e.getSource()== dessert6)
        {
            String name = "Seri Muka";
            int price = 1;
            int qty = Integer.parseInt(JOptionPane.showInputDialog(null,"Please Enter the Quantity","Quantity",JOptionPane.INFORMATION_MESSAGE));
            int tot = price*qty;
            model = (DefaultTableModel)jTable1.getModel();
            model.addRow(new Object[]
            {       
               name,
               price,
               qty,
               tot,
            });
            int sum = 0;
            for(int i = 0; i<jTable1.getRowCount(); i++){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString());
            }    
            txtsub.setText(Integer.toString(sum));
        }
        
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
